logging:
  level:
    root: debug
    sql: debug
    web: debug
  file:
    name: logs/mws.log
    path: logs
app:
  time-to-live-milliseconds: 3000
weather-stack:
  base-url: https://api.weatherstack.com
  url: /current?access_key=%s&query=Melbourne
  key: %WEATHERSTACK_KEY%
open-weather-map:
  base-url: https://api.openweathermap.org
  url: /data/2.5/weather?lat=%s&lon=%s&appid=%s
  key: %OPEN_WEATHERMAP_KEY%
  lat: -37.8140
  lon: 144.9630